[project]
name = "organizationstructure"
version = "0.1.0"
description = ""
authors = [
    {name = "Ivan",email = "ivan-don4encko@ya.ru"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "django (>=6.1,<7.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pillow (>=12.3.0,<13.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]
